/*
 * LeaderElectorRecordTest.java
 *
 * Copyright by toolarium, all rights reserved.
 */
package com.github.toolarium.leader.election.impl.database.dao;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;


/**
 * Test the LeaderElectorRecord.
 *
 * @author patrick
 */
public class LeaderElectorRecordTest {
    private static final String APP_NAME = "myapp";
    private static final String USER1 = "user1";

    /**
     * Test auto-generated id/timestamp constructor.
     */
    @Test
    public void testAutoGeneratedConstructor() {
        final long before = System.currentTimeMillis();
        LeaderElectorRecord record = new LeaderElectorRecord(APP_NAME, "instance1", USER1);
        final long after = System.currentTimeMillis();
        assertNotNull(record.getId());
        assertEquals(APP_NAME, record.getName());
        assertEquals("instance1", record.getInstance());
        assertEquals(USER1, record.getUser());
        assertTrue(record.getTimestamp() >= before && record.getTimestamp() <= after,
                "Timestamp must be epoch-millis within the test window");
    }


    /**
     * Test explicit constructor.
     */
    @Test
    public void testExplicitConstructor() {
        // 2026-01-01T00:00:00Z in epoch millis
        long ts = 1735689600000L;
        LeaderElectorRecord record = new LeaderElectorRecord("fixed-id", APP_NAME, "instance1", USER1, ts);
        assertEquals("fixed-id", record.getId());
        assertEquals(APP_NAME, record.getName());
        assertEquals("instance1", record.getInstance());
        assertEquals(USER1, record.getUser());
        assertEquals(ts, record.getTimestamp());
    }


    /**
     * Test equals and hashCode based on id and name.
     */
    @Test
    public void testEqualsAndHashCode() {
        LeaderElectorRecord a = new LeaderElectorRecord("id1", APP_NAME, "inst1", USER1, 1000L);
        LeaderElectorRecord b = new LeaderElectorRecord("id1", APP_NAME, "inst2", "user2", 2000L);
        LeaderElectorRecord c = new LeaderElectorRecord("id2", APP_NAME, "inst1", USER1, 1000L);

        assertEquals(a, b);
        assertEquals(a.hashCode(), b.hashCode());
        assertNotEquals(a, c);
        assertEquals(a, a);
        assertNotEquals(a, null);
        assertNotEquals(a, "other");
    }


    /**
     * Test toString contains key fields.
     */
    @Test
    public void testToString() {
        LeaderElectorRecord record = new LeaderElectorRecord("id1", APP_NAME, "inst1", USER1, 1000L);
        String s = record.toString();
        assertTrue(s.contains("id1"));
        assertTrue(s.contains(APP_NAME));
        assertTrue(s.contains("inst1"));
        assertTrue(s.contains(USER1));
        assertTrue(s.contains("1000"));
    }
}
