/*
 * LeaderElectorRecordTest.java
 *
 * Copyright by toolarium, all rights reserved.
 */
package com.github.toolarium.leader.election.impl.database.dao;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;


/**
 * Test the LeaderElectorRecord.
 *
 * @author patrick
 */
public class LeaderElectorRecordTest {

    /**
     * Test auto-generated id/timestamp constructor.
     */
    @Test
    public void testAutoGeneratedConstructor() {
        LeaderElectorRecord record = new LeaderElectorRecord("myapp", "instance1", "user1");
        assertNotNull(record.getId());
        assertEquals("myapp", record.getName());
        assertEquals("instance1", record.getInstance());
        assertEquals("user1", record.getUser());
        assertNotNull(record.getTimestamp());
        assertTrue(record.getTimestamp().endsWith("Z"));
    }


    /**
     * Test explicit constructor.
     */
    @Test
    public void testExplicitConstructor() {
        LeaderElectorRecord record = new LeaderElectorRecord("fixed-id", "myapp", "instance1", "user1", "2026-01-01T00:00:00.000Z");
        assertEquals("fixed-id", record.getId());
        assertEquals("myapp", record.getName());
        assertEquals("instance1", record.getInstance());
        assertEquals("user1", record.getUser());
        assertEquals("2026-01-01T00:00:00.000Z", record.getTimestamp());
    }


    /**
     * Test equals and hashCode based on id and name.
     */
    @Test
    public void testEqualsAndHashCode() {
        LeaderElectorRecord a = new LeaderElectorRecord("id1", "myapp", "inst1", "user1", "ts1");
        LeaderElectorRecord b = new LeaderElectorRecord("id1", "myapp", "inst2", "user2", "ts2");
        LeaderElectorRecord c = new LeaderElectorRecord("id2", "myapp", "inst1", "user1", "ts1");

        assertEquals(a, b);
        assertEquals(a.hashCode(), b.hashCode());
        assertNotEquals(a, c);
        assertEquals(a, a);
        assertNotEquals(a, null);
        assertNotEquals(a, "other");
    }


    /**
     * Test toString contains key fields.
     */
    @Test
    public void testToString() {
        LeaderElectorRecord record = new LeaderElectorRecord("id1", "myapp", "inst1", "user1", "ts1");
        String s = record.toString();
        assertTrue(s.contains("id1"));
        assertTrue(s.contains("myapp"));
        assertTrue(s.contains("inst1"));
        assertTrue(s.contains("user1"));
        assertTrue(s.contains("ts1"));
    }
}
